### ISSUE TITLE
I have a problem with code

### ISSUE THREAD

**Issue by mtrzcinska** [smsapi/smsapi-go#2]
Hey, I have a problem with import library.  Excatly about this: " from smsapi.client import SmsApiPlClient ". This is in code and python seeing a problem and told that: Import "smsapi.client" could not be resolvedPylance [reportMissingImports]. Could you help me, what can I do?

**Comment by in-void** [comment]
Hi. You are referring to [smsapi python client](https://github.com/smsapi/smsapi-python-client) in smsapi-go project, this are two different projects. Anyway I guess yours environment is missing smsapi-python-client library.
